-- UP MIGRATION: 20260523214653_usuarioscampos

ALTER TABLE usuarios
ADD COLUMN partidos_apostados INTEGER NOT NULL DEFAULT 0,
ADD COLUMN partidos_ganados INTEGER NOT NULL DEFAULT 0,
ADD COLUMN partidos_perdidos INTEGER NOT NULL DEFAULT 0,
ADD COLUMN puntos INTEGER NOT NULL DEFAULT 0,
ADD COLUMN racha INTEGER NOT NULL DEFAULT 0,
ADD COLUMN win_rate DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN premio_asociado DECIMAL(10, 2) DEFAULT NULL;
