ALTER TABLE partidos
    ADD COLUMN extra_partidazo BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN extra_milagro BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN extra_batacazo BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN extra_el_elegido BOOLEAN NOT NULL DEFAULT FALSE;
